spring:
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.site.blog.entity
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: "tb_"

#自定义日志打印包路径
jaytan:
  log:
    basePkg: execution(* space.pst.jaytan.blog.controller..*.*(..))

#redis 相关配置
# Redis开关/默认关闭
spring.redis.enabled: true
spring.redis.database: 0
spring.redis.host: 120.24.90.121
spring.redis.port: 18879
spring.redis.password: jaytan@123
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.lettuce.pool.max-active: 100
# 连接池中的最大空闲连接
spring.redis.lettuce.pool.max-idle: 100
# 连接池中的最小空闲连接
spring.redis.lettuce.pool.min-idle: 50
spring.redis.lettuce.pool.max-wait: 6000
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.lettuce.pool.timeout: 10000

jaytan.door.black.basePackage: execution(* space.pst.jaytan.starter.example.biz..*.*(..))

#自定义日志打印包路径
#jaytan.log.basePkg: execution(* space.pst.jaytan.starter.example.api..*.*(..))