spring:
  profiles:
    active: prod

mybatis-plus:
  type-aliases-package: com.site.blog.entity
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: "tb_"


